services:
  db:
    image: ankane/pgvector
    container_name: pgvector_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ragdb
    ports:
      - "5433:5432"